### ISSUE TITLE
Bug-Intermittently - Clicking on Gender List Box , terminates the application abruptly without any indication 

### ISSUE THREAD

**Issue by balasubramanian-dt** [dptstech/dpts-aushadam#2]
**Intermittently - Clicking on Gender List Box , terminates the application abruptly without any indication** 
           Error shown in Terminal
           ==================
       	File "/home/admin/Documents/dpts-aushadam/Views/Patientview.kv", line 59, in <module>on_release: dd_genderlist.open(self)
       	File "kivy/weakproxy.pyx", line 30, in kivy.weakproxy.WeakProxy.__getattr__
       	File "kivy/weakproxy.pyx", line 26, in kivy.weakproxy.WeakProxy.__ref__ ReferenceError: weakly-referenced object no longer exists

**Comment by Lavanya-nk** [comment]
Could you please provide exact scenario to replicate

**Comment by balasubramanian-dt** [comment]
The issue occurred to me when i was testing the application for the bug fixes

1. Open the application, trying to create a new patient record
2. Specify valid Patient Name, Mobile Number, Alternate Mobile Number, Email address
3. Clicking on the Gender list box, terminates / crashes the application with the following error shown in the terminal window

"Traceback (most recent call last):
   File "aushadam.py", line 120, in <module>
     ClinicManagementSystem().run()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 826, in run
     runTouchApp()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 340, in idle
     self.dispatch_input()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 325, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 291, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
   File "/usr/lib/python3/dist-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1098, in kivy._event.EventObservers._dispatch
   File "/usr/lib/python3/dist-packages/kivy/lang/builder.py", line 64, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "/home/admin/Documents/dpts-aushadam/Views/Patientview.kv", line 61, in <module>
     on_release: dd_genderlist.open(self)
   File "kivy/weakproxy.pyx", line 30, in kivy.weakproxy.WeakProxy.__getattr__
   File "kivy/weakproxy.pyx", line 26, in kivy.weakproxy.WeakProxy.__ref__
 ReferenceError: weakly-referenced object no longer exists

**Comment by balasubramanian-dt** [comment]
Not able to reproduce as on current date 12-10-2020 and can be closed
